stages:
  - build_and_deploy

deploy_multiplayer:
  stage: build_and_deploy
  tags:
    - nodejs
  script:
    - echo "🚀 Memulai Build Colyseus (Server) & Vite (Client)..."

    # 1. Build Client (Vite)
    - cd client && npm install && npm run build && cd ..

    # 2. Build Server (Colyseus) - INI YANG KURANG TADI!
    - cd server && npm install && npm run build && cd ..

    # 3. Kirim Hasil ke aaPanel
    - rsync -az --delete ./server/public/ root@192.168.1.157:/www/wwwroot/MultiplayerGameQuiz/
    - rsync -az --delete ./server/ root@192.168.1.157:/www/wwwroot/MultiplayerGameQuiz/server/
    - rsync -az --delete ./shared/ root@192.168.1.157:/www/wwwroot/MultiplayerGameQuiz/shared/

    # 4. Eksekusi di Server
    - ssh -o StrictHostKeyChecking=no root@192.168.1.157 "
        chown -R www:www /www/wwwroot/MultiplayerGameQuiz && 
        cd /www/wwwroot/MultiplayerGameQuiz/server && 
        sudo -u www npm install --production --no-audit --cache /tmp/npm-cache-multi && 
        sudo -u www pm2 startOrReload ecosystem.config.js --update-env &&
        echo '✅ Colyseus Server & Vite Client Berhasil Update!'
      "
  only:
    - main